server:
  port: 8001

spring:
  application:
#    微服务名
    name: cloud-payment-service
  datasouse:
    type: com.alibaba.druid.pool.DruidDataSouse
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/springCloud?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: "gqs123456"


eureka:
  client:
    #表示是否将自己注册进入eurekaserver，默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true，单点无所谓，集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
  instance:
    instance-id: ${spring.application.name}-${server.port} #改写注册成功后在管理页面显示的服务的名字